### ISSUE TITLE
Dictionaries not included

### ISSUE THREAD

**Issue by Mcx002** [ariaghora/mpstemmer#3]
![image](https://github.com/ariaghora/mpstemmer/assets/68631992/8448bb66-c88d-4bbe-a489-af67c1a93aaf)

turned out error
![image](https://github.com/ariaghora/mpstemmer/assets/68631992/34d62913-3b52-4835-919b-f4bac39a99d6)

**Comment by Mcx002** [comment]
I forked the project, and solve the problem, you can check it out https://github.com/Mcx002/mpstemmer
It is just because the manifest file name is not UPPERCASE, and just because of that it won't be included
btw this is happened when I used virtual env (venv). I didn't try it on conda or any else virtual env

**Comment by ariaghora** [comment]
Thanks! I reproduced that error at my end too. Sorry, I was busy with other stuffs just to check this. Will merge.
